In [6]:
import numpy as np

In [3]:
np.random.randint(1,15)

3

In [25]:
np.choose?

In [ ]:
b
i
n
g
o

In [2]:
def bingo_range(start):
    return [x for x in range(start,start+15)]

In [3]:
def bingo_numbers():
    bingo_nbrs = {}
    start = 1
    bingo_nbrs['b'] = bingo_range(start)
    start+=15
    bingo_nbrs['i'] = bingo_range(start)
    start+=15
    bingo_nbrs['n'] = bingo_range(start)
    start+=15
    bingo_nbrs['g'] = bingo_range(start)
    start+=15
    bingo_nbrs['o'] = bingo_range(start)
    return bingo_nbrs

In [4]:
bingo_nbrs = bingo_numbers()

In [5]:
bingo_nbrs

{'b': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
 'i': [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
 'n': [31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
 'g': [46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
 'o': [61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75]}

In [ ]:
# Generate a Card

In [19]:
def generate_card(bingo_nbrs):
    card = []
    for k in bingo_nbrs.keys():
        card.append(np.random.choice(bingo_nbrs[k],5,replace=False))
    return card

In [17]:
np.random.choice(bingo_nbrs['b'],5,replace=False)

array([13,  8,  5,  3,  2])

In [42]:
generate_card(bingo_nbrs)

[array([ 7, 11,  4, 14,  6]),
 array([24, 17, 20, 27, 19]),
 array([42, 39, 44, 32, 34]),
 array([58, 47, 55, 51, 48]),
 array([63, 69, 70, 62, 61])]

[array([11, 13,  7, 10,  6]),
 array([29, 25, 30, 18, 17]),
 array([43, 32, 42, 33, 39]),
 array([58, 47, 53, 56, 52]),
 array([75, 64, 74, 69, 62])]

ValueError: invalid literal for int() with base 10: '*'

In [ ]:
# Pick Numbers

In [3]:
selected_number = []

In [1]:
def picked_number(selected_number, new_number):
    selected_number.append(new_number)

In [13]:
picked_number(selected_number, np.random.randint(1,36))
print(selected_number)

[2, 30, 20, 16, 13, 19, 8, 14]


In [17]:
class Bingo:
    def __init__(self):
        self.game_number = 0
        self.selected_numbers = []
        
    def picked_number(self, new_number):
        self.selected_numbers.append(new_number)
    
    def pick_random_number(self):
        return np.random.randint(1,36)

In [18]:
bingo = Bingo()

In [30]:
nbr = bingo.pick_random_number()
bingo.picked_number(nbr)
print(bingo.selected_numbers)

[26, 31, 5, 31, 10, 23, 6, 15, 33, 10, 16, 1]


In [43]:
from src.bingo import Bingo 
from src.bingo import Card 

In [46]:
card = Card()

In [47]:
card.card_numbers

[array([14,  2,  9, 15, 13]),
 array([30, 17, 22, 21, 24]),
 array([43, 35, 37, 36, 38]),
 array([55, 54, 52, 57, 50]),
 array([74, 71, 61, 70, 65])]

In [49]:
import pandas as pd


In [39]:
%load_ext autoreload

In [45]:
%autoreload

In [53]:
current_card = np.array(card.card_numbers)

In [54]:
current_card.T

array([[14, 30, 43, 55, 74],
       [ 2, 17, 35, 54, 71],
       [ 9, 22, 37, 52, 61],
       [15, 21, 36, 57, 70],
       [13, 24, 38, 50, 65]])

In [ ]:
current_card.T