In [1]:
import numpy as np

In [2]:
def bingo_range(start):
    return [x for x in range(start,start+15)]

In [3]:
def bingo_numbers():
    bingo_nbrs = {}
    start = 1
    bingo_nbrs['b'] = bingo_range(start)
    start+=15
    bingo_nbrs['i'] = bingo_range(start)
    start+=15
    bingo_nbrs['n'] = bingo_range(start)
    start+=15
    bingo_nbrs['g'] = bingo_range(start)
    start+=15
    bingo_nbrs['o'] = bingo_range(start)
    return bingo_nbrs

In [4]:
bingo_nbrs = bingo_numbers()

In [5]:
bingo_nbrs

{'b': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
 'i': [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
 'n': [31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
 'g': [46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
 'o': [61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75]}

# Generate a Card

In [19]:
def generate_card(bingo_nbrs):
    card = []
    for k in bingo_nbrs.keys():
        card.append(np.random.choice(bingo_nbrs[k],5,replace=False))
    return card

In [17]:
np.random.choice(bingo_nbrs['b'],5,replace=False)

array([13,  8,  5,  3,  2])

In [42]:
generate_card(bingo_nbrs)

[array([ 7, 11,  4, 14,  6]),
 array([24, 17, 20, 27, 19]),
 array([42, 39, 44, 32, 34]),
 array([58, 47, 55, 51, 48]),
 array([63, 69, 70, 62, 61])]

# Pick Numbers

In [3]:
selected_number = []

In [1]:
def picked_number(selected_number, new_number):
    selected_number.append(new_number)

In [13]:
picked_number(selected_number, np.random.randint(1,36))
print(selected_number)

[2, 30, 20, 16, 13, 19, 8, 14]


In [17]:
class Bingo:
    def __init__(self):
        self.game_number = 0
        self.selected_numbers = []
        
    def picked_number(self, new_number):
        self.selected_numbers.append(new_number)
    
    def pick_random_number(self):
        return np.random.randint(1,36)

In [18]:
bingo = Bingo()

In [30]:
nbr = bingo.pick_random_number()
bingo.picked_number(nbr)
print(bingo.selected_numbers)

[26, 31, 5, 31, 10, 23, 6, 15, 33, 10, 16, 1]


In [11]:
from src.bingo import Bingo 
from src.bingo import Card 

In [26]:
%load_ext autoreload

In [27]:
%autoreload

In [27]:
card = Card()

In [28]:
card.card_numbers

array([[12,  5,  2,  7, 15],
       [19, 16, 23, 20, 30],
       [44, 39,  0, 32, 42],
       [57, 60, 56, 51, 55],
       [65, 74, 66, 64, 68]])

In [20]:
card.card_numbers[2][2]=0

In [29]:
card.card_numbers.T

array([[12, 19, 44, 57, 65],
       [ 5, 16, 39, 60, 74],
       [ 2, 23,  0, 56, 66],
       [ 7, 20, 32, 51, 64],
       [15, 30, 42, 55, 68]])

In [49]:
import pandas as pd


In [39]:
%load_ext autoreload

In [45]:
%autoreload

In [53]:
current_card = np.array(card.card_numbers)

In [54]:
current_card.T

array([[14, 30, 43, 55, 74],
       [ 2, 17, 35, 54, 71],
       [ 9, 22, 37, 52, 61],
       [15, 21, 36, 57, 70],
       [13, 24, 38, 50, 65]])

In [ ]:
current_card.T

# Generate Card IDs

In [6]:
import string
from datetime import datetime

In [38]:
from pymongo import MongoClient

In [9]:
letters = string.ascii_lowercase

In [83]:
def generateCardCode(times=100, code_len=6):
    code_list = []
    for t in range(0, times):
        code = ""
        for n in range(0,code_len):
            nl = np.random.randint(0,2)
            if nl==0:
               #number
                num = np.random.randint(0,10)
                code+=str(num)
            elif nl==1:
                let = np.random.randint(0,26)
                code+=letters[let]
        code_list.append(code)
    return code_list

In [38]:
codes = generateCardCode(15, code_len=6)

In [39]:
c = MongoClient()

In [40]:
c.list_database_names()

['Galvanize',
 'admin',
 'bingo',
 'clicks',
 'config',
 'evil',
 'local',
 'metroid',
 'nyt_dump',
 'unicorns',
 'yelp']

In [49]:
col = db.create_collection('card_ids')

In [50]:
col.find()

In [42]:
db.bingo.card_ids.insert_one?

Object `db.bingo.card_ids.insert_one` not found.


In [55]:
for c in codes:
    print({'Code': c, 'used': False})
    db.card_ids.insert_one({'Code': c, 'used': False})

{'Code': '93lx67', 'used': False}
{'Code': 'ij4203', 'used': False}
{'Code': 'j33394', 'used': False}
{'Code': '15y5s8', 'used': False}
{'Code': 'lq80qr', 'used': False}
{'Code': '22xsol', 'used': False}
{'Code': 'pty123', 'used': False}
{'Code': 'yy4z5d', 'used': False}
{'Code': '0n13l6', 'used': False}
{'Code': 'hq39e3', 'used': False}
{'Code': 'onl7ax', 'used': False}
{'Code': '70l9np', 'used': False}
{'Code': '3efd2z', 'used': False}
{'Code': '9c1eu9', 'used': False}
{'Code': 'wyn8u4', 'used': False}


In [50]:
card = c.bingo.card_ids.find_one({'Code': '93lx67x'})

In [52]:
type(card)

NoneType

In [79]:
for doc in db.card_ids.find({}):
    print(doc)

{'_id': ObjectId('5cac20ae3d38dc4e1d2b5382'), 'Code': '93lx67', 'used': False}
{'_id': ObjectId('5cac20ae3d38dc4e1d2b5383'), 'Code': 'ij4203', 'used': True}
{'_id': ObjectId('5cac20ae3d38dc4e1d2b5384'), 'Code': 'j33394', 'used': False}
{'_id': ObjectId('5cac20ae3d38dc4e1d2b5385'), 'Code': '15y5s8', 'used': False}
{'_id': ObjectId('5cac20ae3d38dc4e1d2b5386'), 'Code': 'lq80qr', 'used': False}
{'_id': ObjectId('5cac20ae3d38dc4e1d2b5387'), 'Code': '22xsol', 'used': False}
{'_id': ObjectId('5cac20ae3d38dc4e1d2b5388'), 'Code': 'pty123', 'used': False}
{'_id': ObjectId('5cac20ae3d38dc4e1d2b5389'), 'Code': 'yy4z5d', 'used': False}
{'_id': ObjectId('5cac20ae3d38dc4e1d2b538a'), 'Code': '0n13l6', 'used': False}
{'_id': ObjectId('5cac20ae3d38dc4e1d2b538b'), 'Code': 'hq39e3', 'used': False}
{'_id': ObjectId('5cac20ae3d38dc4e1d2b538c'), 'Code': 'onl7ax', 'used': False}
{'_id': ObjectId('5cac20ae3d38dc4e1d2b538d'), 'Code': '70l9np', 'used': False}
{'_id': ObjectId('5cac20ae3d38dc4e1d2b538e'), 'Code':

In [77]:
res = db.card_ids.find_one({'Code': 'ij4203'})
print(res)

{'_id': ObjectId('5cac20ae3d38dc4e1d2b5383'), 'Code': 'ij4203', 'used': True}


In [78]:
if res==None:
    print("Card Not Found.")
else:
    if res['used']==True:
        print("Card Already Used.")
    else:
        print("Use this Card.")

Card Already Used.


In [75]:
db.card_ids.update_one({'Code': 'ij4203'}, {'$set': {'used': True}})

In [73]:
db.card_ids.update_one?

# Link Card Code to User

In [10]:
players = db.create_collection('users')

NameError: name 'db' is not defined

In [84]:
generateCardCode(1, code_len=32)

['w9iao0t279ed2mq20webmjvm3g574t66']

In [86]:
datetime.now()

datetime.datetime(2019, 4, 8, 21, 53, 0, 165045)

In [87]:
db.players.insert_one(
    {'user_id': 'steve.griswold',
     'secret_key': 'test123',
     'temp_key': 'w9iao0t279ed2mq20webmjvm3g574t66',
     'start_time': datetime.now()})

In [149]:
for p in db.players.find():
    print(p)

{'_id': ObjectId('5cac25383d38dc4e1d2b5391'), 'user_id': 'steve.griswold', 'secret_key': 'test123', 'temp_key': '530548we35yhxi62q7ehxp275331r507', 'start_time': datetime.datetime(2019, 4, 8, 22, 2, 23, 912000), 'nickname': 'SpongeBob'}


In [103]:
def validate_user(user_id, secret_key):
    res = db.players.find_one({'user_id': user_id, 'secret_key': secret_key})
    if res==None:
        res=db.players.find_one({'user_id': user_id})
        if res==None:
            print('Player Not Registered.')
        else:
            print('Incorrect Secret Key.')
    else:
        keys = generateCardCode(1, 32)
        db.players.update_one(
            {'user_id': user_id, 'secret_key': secret_key},
            {'$set': {'temp_key': keys[0], 'start_time': datetime.now()}})
        print(keys[0])

In [106]:
validate_user('steve.griswold', 'test123')

530548we35yhxi62q7ehxp275331r507


# Update Nickname

In [120]:
from datetime import datetime

In [144]:
def getStamp(user_id, temp_key):
    res =db.players.find_one({'user_id': user_id, 'temp_key': temp_key})
    if res!=None:
        time = res['start_time']
        time_diff = datetime.now() - time
        if (time_diff.total_seconds()/60/60) > 2:
            print("time out")
            return False
        else:
            return True

In [145]:
getStamp('steve.griswold', '530548we35yhxi62q7ehxp275331r507')

True

In [19]:
user_id = 'steve.griswold'
temp_key = '530548we35yhxi62q7ehxp275331r507'
secret_key = 'test123'

In [147]:
def setnickname(user_id, temp_key, nickname):
    if getStamp(user_id, temp_key):
        res = db.players.find_one({'user_id': user_id, 'temp_key': temp_key})
        if res==None:
            res=db.players.find_one({'user_id': user_id})
            if res==None:
                print('Oops Something went wrong.  Login Again.')
            else:
                print('Temp Key Expired.  Login Again.')
        else:
            db.players.update_one(
                {'user_id': user_id, 'temp_key': temp_key},
                {'$set': {'nickname': nickname}})
            print('Updated nickname:', nickname)
    else:
        print('Inactive: Login Again')

In [4]:
setnickname(user_id, temp_key, 'SpongeBob')

NameError: name 'setnickname' is not defined

In [29]:
from src.bingo import bingoDB

In [30]:
db = bingoDB()

In [8]:
user_id = 'steve.griswold'
secret_key = 'test123'
temp_key = '530548we35yhxi62q7ehxp275331r507'

In [22]:
ret = db.players.find_one({'user_id': user_id, 'secret_key': secret_key},{'temp_key': True})

ret['temp_key']

In [9]:
db.getTempKey(user_id, secret_key)

'b9q880kd22qp8af5nu75ra4tmo9q2jnw'

In [1]:
%load_ext autoreload

In [28]:
%autoreload

In [31]:
user = db.welcome(user_id, secret_key)

In [26]:
if 'cards' in user.keys():
    cards = user['cards']
else:
    cards = None

In [32]:
user

{'_id': ObjectId('5cac25383d38dc4e1d2b5391'),
 'temp_key': 'b9q880kd22qp8af5nu75ra4tmo9q2jnw',
 'nickname': 'SpongeBob'}

In [34]:
c.card_ids.find({})

NameError: name 'c' is not defined

In [36]:
c.card_ids.find_one({})

NameError: name 'c' is not defined